export const films = [
  {
    title: "The Big Lebowski",
    description: "Description of Film ",
    year: 1998,
    image: "images/the-big-lebowski.jpg",
  },
  {
    title: "Pulp Fiction",
    description: "Description of Film ",
    year: 1994,
    image: "images/pulpfiction.webp",
  },
  {
    title: "Jurassic Park ",
    description: "Description of Film ",
    year: 1993,
    image: "images/JurrassicPark.webp",
  },
  {
    title: "Once upon a time hollywood",
    description: "Description of Film ",
    year: 2019,
    image: "images/onceuponatimehollywood.webp",
  },
  {
    title: "Alien",
    description: "Description of Film ",
    year: 1979,
    image: "images/Alien.webp",
  },
  {
    title: "jaws",
    description: "Description of Film ",
    year: 1975,
    image: "images/jaws.jpg",
  },
  {
    title: "End game",
    description: "Description of Film ",
    year: 2019,
    image: "images/Endgame.webp",
  },
  {
    title: "Friday",
    description: "Description of Film ",
    year: 1995,
    image: "images/friday.webp",
  },
  {
    title: "Halloween",
    description: "Description of Film ",
    year: 1978,
    image: "images/halloween.webp",
  },
  {
    title: "Scream",
    description: "Description of Film ",
    year: 1996,
    image: "images/Scream.webp",
  },
  {
    title: "Star wars",
    description: "Description of Film ",
    year: 1977,
    image: "images/starwars.webp",
  },
  {
    title: "Top gun",
    description: "Description of Film ",
    year: 1986,
    image: "images/topgun.webp",
  },
  {
    title: "Back to the future",
    description: "Description of Film ",
    year: 1985,
    image: "images/backtothefuture.webp",
  },
  {
    title: "ET",
    description: "Description of Film ",
    year: 1982,
    image: "images/ET.webp",
  },
  {
    title: "Rocky",
    description: "Description of Film ",
    year: 1976,
    image: "images/Rocky.webp",
  },
  {
    title: "Alpacino scarface",
    description: "Description of Film ",
    year: 1983,
    image: "images/Aloacino.webp",
  },
  {
    title: "Return of the Jedi",
    description: "Description of Film ",
    year: 1983,
    image: "images/star-wars-episode-vi-return-of-the-jedi.webp",
  },
  {
    title: "Goodfells",
    description: "Description of Film ",
    year: 1990,
    image: "images/Goodfells.webp",
  },
  {
    title: "The terminator",
    description: "Description of Film ",
    year: 1984,
    image: "images/the-terminator.jpg",
  },
  {
    title: "The godfather",
    description: "Description of Film ",
    year: 1972,
    image: "images/the-godfather.jpg",
  },
];
